import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="font-Inter h-screen w-full bg-gray-800">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex text-white">
        <div className="w-5/6 justify-center space-x-0 pt-8 md:flex md:w-5/6 md:space-x-16 md:pt-32 xl:w-3/4">
          <Sidebar />

          <div className="my-8 w-full text-4xl md:my-0 md:w-2/3">
            <h1>Index</h1>
          </div>
        </div>
      </main>
    </div>
  );
}
