import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";
import IndexContent from "../components/IndexContent";

export default function Home() {
  return (
    <div className="font-Inter h-full min-h-screen w-full bg-gray-800">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white">
        <div className="mx-auto h-full w-5/6 space-x-0 pt-8 md:flex md:w-5/6 md:space-x-16 md:pt-32 xl:w-3/4">
          <Sidebar />
          <IndexContent />
        </div>
      </main>
    </div>
  );
}
