import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Sidebar from '../components/Sidebar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-gray-800 w-full h-screen font-Inter">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white">
        <div className='pt-8 md:pt-32 md:flex w-3/4 m-auto space-x-0 md:space-x-16'>

          <Sidebar />

            <div className='text-4xl w-full my-8 md:my-0 md:w-2/3'>
                <h1>Index</h1>
            </div>
        </div>
      </main>
    </div>
  )
}
