import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import PortfolioContent from '../components/PortfolioContent'
import Sidebar from '../components/Sidebar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-gray-800 min-h-screen w-full h-full font-Inter">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white">
        <div className='pt-8 md:pt-32 md:flex w-3/4 mx-auto space-x-0 md:space-x-16'>

            <Sidebar />
            <PortfolioContent />
        </div>
      </main>
    </div>
  )
}